version: "3"
services:
  app:
    build:
      context: .
      dockerfile: image/Dockerfile
    volumes:
      - ".:/code"
      - "node_modules:/code/node_modules"
    command:
      - yarn
      - serve
      - --host=0.0.0.0
    ports:
      - 8080:8080
  ui:
    build:
      context: .
      dockerfile: image/Dockerfile
    volumes:
      - ".:/code"
      - "node_modules:/code/node_modules"
    command:
      - vue
      - ui
      - --host=0.0.0.0
      - --port=8081
    ports:
      - 8081:8081
volumes:
  node_modules:
